
# Tempo of trait evolution. 

Phylogenetic trees are inherently visual hypotheses. They tell us about evolutionary relationships through their arrangement of tips, nodes, and branching patterns. They also tell us something about relative amount of evolutionary change through their branch lengths. Longer branches have had more time for a lineages' (species') attributes to change. 

One common use for phylogenetic trees beyond describing the relatedness of a group of organisms, is to estimate rates of trait evolution. Maybe we want to know: **how rapidly is vision lost among cave dwelling fish?** Or **how often have insects lost or gained flight?** To address questions like these we start with a null model of constant evolution rates through time. In [1999 Mark Pagel](https://www.nature.com/articles/44766) proposed three statistical models that can be thought of as branch length transformations (lamda: $\lambda$, delta: $\delta$, and kappa: $\kappa$). Each can be used to test for deviations from a constant rate of evolution. The models work by transforming the phylogenetic variance covariance matrix which is essentially the tree represented as a matrix of pairwise distances among all tips and nodes. 

